var tables = [
    {
        "id":1,
        "name":"Table-1",
        "totalCost":0,
        "numberOfItems":0,
        "orders":{}
    },
    {
        "id":2,
        "name":"Table-2",
        "totalCost":0,
        "numberOfItems":0,
        "orders":{}
    },
    {
        "id":3,
        "name":"Table-3",
        "totalCost":0,
        "numberOfItems":0,
        "orders":{}
    },
    {
        "id":4,
        "name":"Table-4",
        "totalCost":0,
        "numberOfItems":0,
        "orders":{}
    },
    {
        "id":5,
        "name":"Table-5",
        "totalCost":0,
        "numberOfItems":0,
        "orders":{}
    }
];